export const INIT = "INIT";
export const PRODUCT_INIT = "PRODUCT_INIT";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_COMPLETE = "FETCH_PRODUCT_COMPLETE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT_INIT = "EDIT_PRODUCT_INIT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const SUBMIT_EDIT_PRODUCT = "SUBMIT_EDIT_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_FINISH = "ADD_PRODUCT_FINISH";
export const ADD_PRODUCT_INIT = "ADD_PRODUCT_INIT";
export const FETCH_SORTED_PRODUCT_COMPLETE = "FETCH_SORTED_PRODUCT_COMPLETE";
export const INITIAL_LOAD_TIME_EXCEED = "INITIAL_LOAD_TIME_EXCEED";


